import { INode, INodeData, INodeParams } from '../../../src/Interface'
import { getBaseClasses, stripHTMLFromToolInput } from '../../../src/utils'
import { RequestParameters, desc, RequestsPutTool } from './core'

const codeExample = `{
    "name": {
        "type": "string",
        "required": true,
        "description": "Name of the item"
    },
    "date": {
        "type": "string",
        "description": "Date of the item"
    }
}`

class RequestsPut_Tools implements INode {
    label: string
    name: string
    version: number
    description: string
    type: string
    icon: string
    category: string
    baseClasses: string[]
    inputs: INodeParams[]

     {
        this.label = 'Requests Put'
        this.name = 'requestsPut'
        this.version = 1.0
        this.type = 'RequestsPut'
        this.icon = 'put.png'
        this.category = 'Tools'
        this.description = 'Execute HTTP PUT requests'
        th, 'Tool']
        this.inputs = [
            {
                label: 'URL',
                name: 'requestsPutUrl',
                type: 'string',
                acceptVariable: true
            },
            {
                label: 'Name',
                name: 'requestsPutName',
                type: 'string',
                default: 'requests_put',
                description: 'Name of the tool',
                additionalParams: true,
                optional: true
            },
            {
                label: 'Description',
                name: 'requestsPutDescription',
                type: 'string',
                rows: 4,
                default: desc,
                description: 'Describe to LLM when it should use this tool',
                additionalParams: true,
                optional: true
            },
            {
                label: 'Headers',
                name: 'requestsPutHeaders',
                type: 'string',
                rows: 4,
                acceptVariable: true,
                additionalParams: true,
                optional: true,
                placeholder: `{
    "Authorization": "Bearer <token>"
}`
            },
            {
                label: 'Body',
                name: 'requestPutBody',
                type: 'string',
                rows: 4,
                description: 'JSON body for the PUT request. This will override the body generated by the LLM',
                additionalParams: true,
                acceptVariable: true,
                optional: true,
                placeholder: `{
    "name": "John Doe",
    "age": 30
}`
            },
            {
                label: 'Body Schema',
                name: 'requestsPutBodySchema',
                type: 'code',
                description: 'Description of the available body params to enable LLM to figure out which body params to use',
                placeholder: `{
    "name": {
        "type": "string",
        "required": true,
        "description": "Name of the item"
    },
    "date": {
        "type": "string",
        "description": "Date of the item"
    }
}`,
                optional: true,
                hideCodeExecute: true,
                additionalParams: true,
                codeExample: codeExample
            },
            {
                label: 'Max Output Length',
                name: 'requestsPutMaxOutputLength',
                type: 'number',
                description: 'Max length of the output. Remove this if you want to return the entire response',
                default: '2000',
                step: 1,
                optional: true,
                additionalParams: true
            }
        ]
    }

    a: Promise<any> {
         || (n
         || (n
         || (n
         || (n
         || (n
        const bodySchema = nodeData.inputs?.requestsPutBodySchema as string
         || (n

        const obj: RequestParameters = {}
         
         obj.description = description
        
            obj.name = name
                .t
                .
                .
         
         
         {
            )
            obj.headers = parsedHeaders
        }
         {
            
            obj.body = parsedBody
        }

        
    }
}

module.exports = { nodeClass: RequestsPut_Tools }
